kind: Deployment
apiVersion: apps/v1
metadata:
  name: admission-controller-certificate
  namespace: admission-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller-certificate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: admission-controller-certificate
    spec:
      containers:
        - name: admission-controller-certificate
          image: >-
            image-registry.openshift-image-registry.svc:5000/admission-namespace/admission-controller-cert:latest
          ports:
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
          - name: certificate-admission-webhook-tls
            mountPath: /opt/app-root/tls/
            readOnly: true
          env:
            - name: issuer
              value: googlecasclusterissuer-sample
            - name: issuer-group
              value: cas-issuer.jetstack.io
            - name: issuer-kind
              value: GoogleCASClusterIssuer
      serviceAccountName: admission-sa-certificate
      serviceAccount: admission-sa-certificate
      volumes:
      - name: certificate-admission-webhook-tls
        secret: 
          secretName: certificate-admission-webhook-tls