kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-sa-rolebinding-certificate
subjects:
  - kind: ServiceAccount
    name: admission-sa-certificate
    namespace: admission-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-sa-role-certificate
